apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketmonitor
  namespace: marketmonitor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: marketmonitor.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ui-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-frontend
                port:
                  number: 8501
